### ISSUE TITLE
Block list

### ISSUE THREAD

**Issue by jamesgeddes** [bdougie/take-action#11]
### User story
As a repo admin, I want to block specific usernames from being able to assign an issue to themselves, so that my bot accounts can tell human contributors to use the take-action command without assigning the issue to a bot.

### Requirement
Allow users to provide a block list to prevent specific GitHub usernames from self-assigning issues.

**Comment by bdougie** [comment]
hey @jamesgeddes, thanks for the PR. After thinking through the approach, I think adding accounts like name[bot] to an auto block list would be better. But l[imiting interactions](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository) is already a feature on GitHub. Would that already cover a block list use case?

**Comment by jamesgeddes** [comment]
I did not know GutHub actions came with a block list, so yes, that would certainly be better than doing it in bash. 

What did you think about using guard clauses?

**Comment by jamesgeddes** [comment]
Looks like GitHub interaction limits are time limited?

**Comment by jamesgeddes** [comment]
Also, it would probably be bad to block all `*bot*` names due to the number of humans who have this in their name.

https://www.babynamespedia.com/names/boy/bot-end

**Comment by bdougie** [comment]
I suppose they are time-limiting. That feature was created to limit spam during times like Hacktoberfest. Let's go with your PR as-is, based on that knkowledge.

re: bot, all common bots on GitHub have the naming convention, `[bot]` in the name. As long as some don't have square brackets, we would be fine. 

If you are interested, we can include a second PR to auto-block `[bot]`'s.
