### ISSUE TITLE
Block assigning if "needs-triage" or similar label is present on issue

### ISSUE THREAD

**Issue by bdougie** [bdougie/take-action#20]
Will triage this in the future but it came up via Twitter 

https://twitter.com/bdougieyo/status/1630070959465185282?s=46&t=0owJlfkLuep9ISdvDKzq4A

**Comment by a0m0rajab** [comment]
This could be done with: 

` if: ${{ github.event.label.name == 'bug' }}`

https://stackoverflow.com/questions/62325286/run-github-actions-when-pull-requests-have-a-specific-label

**Comment by nickytonline** [comment]
@bdougie, as discussed, I can work on this.
