### ISSUE TITLE
Action will not assign user if another user is assigned. 

### ISSUE THREAD

**Issue by bdougie** [bdougie/take-action#3]
Maybe do this in bash or move to another language....

**Comment by lktslionel** [comment]
Hello @bdougie,
What should be the expected behavior? The actions should fail or just pass/skip if the issue is already assigned?

**Comment by blackgirlbytes** [comment]
.take

**Comment by mtfoley** [comment]
@bdougie I think you should assign Rizelle to this one.
@blackgirlbytes I did some playing around with this in bash.  Maybe this will help:
```bash
# simulate issue fetch payload https://docs.github.com/en/rest/reference/issues#get-an-issue
$ EMPTY='{"assignees":[]}'
$ ASSIGNED='{"assignees":[{"login":"user1"}]}'
# assign variable for username of person trying to self-assign.
$ USER=user2
# this one simulates for an unassigned issue
$ echo $EMPTY | jq '.assignees | map(. | select(.login!="$USER")) | length > 0'
false
# this one is the key piece. it means count the users assigned that aren't the one who's trying to self-assign.
# if true, the issue has already been assigned to someone else
$ echo $ASSIGNED | jq '.assignees | map(. | select(.login!="$USER")) | length > 0'
true
# if false, it means we can assign it
$ echo $ASSIGNED | jq '.assignees | map(. | select(.login!="user1")) | length > 0'
false
```

**Comment by blackgirlbytes** [comment]
thank you @mtfoley

**Comment by mtfoley** [comment]
> @bdougie I think you should assign Rizelle to this one.
> 
> @blackgirlbytes I did some playing around with this in bash.  Maybe this will help:
> 
> ```bash
> 
> # simulate issue fetch payload https://docs.github.com/en/rest/reference/issues#get-an-issue
> 
> $ EMPTY='{"assignees":[]}'
> 
> $ ASSIGNED='{"assignees":[{"login":"user1"}]}'
> 
> # assign variable for username of person trying to self-assign.
> 
> $ USER=user2
> 
> # this one simulates for an unassigned issue
> 
> $ echo $EMPTY | jq '.assignees | map(. | select(.login!="$USER")) | length > 0'
> 
> false
> 
> # this one is the key piece. it means count the users assigned that aren't the one who's trying to self-assign.
> 
> # if true, the issue has already been assigned to someone else
> 
> $ echo $ASSIGNED | jq '.assignees | map(. | select(.login!="$USER")) | length > 0'
> 
> true
> 
> # if false, it means we can assign it
> 
> $ echo $ASSIGNED | jq '.assignees | map(. | select(.login!="user1")) | length > 0'
> 
> false
> 
> ```

And this was too complicated... I think this line should return true if it's OK to assign the issue.

```bash
$ echo $ISSUE_JSON | jq '.assignees | length == 0'

```

**Comment by blackgirlbytes** [comment]
thanks @mtfoley !! I made a PR based on the tips you gave. I really appreciate that one liner. Genius! My bash skills aren't great

**Comment by mtfoley** [comment]
> thanks @mtfoley !! I made a PR based on the tips you gave. I really appreciate that one liner. Genius! My bash skills aren't great

They're fun to work on and can be pretty satisfying when you pipe them together. Here's a totally unrelated gist of some bash I was playing around with this afternoon to look at tag popularity on latest dev.to posts:
https://gist.github.com/mtfoley/881671712965ef6d6349ae16890f9432

**Comment by bdougie** [comment]
Thanks for picking this up @blackgirlbytes. Hoping this will make the Hot Open Sauced repo more approachable.
